Updated build pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,30 +3,6 @@ name: build
 on: [push, pull_request]
 
 jobs:
-  analyze:
-    name: Static Analysis
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: '>=1.22'
-
-      - name: Set up linters
-        run: make install-tools
-
-      - name: Lint
-        run: |
-          make vet
-          make lint
-          make fmt
-          git diff
-          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
-
   build:
     name: Build
     runs-on: ubuntu-latest
@@ -35,13 +11,13 @@ jobs:
         goVer: [1.22, 1.23, 1.24]
     steps:
       - name: Set up Go ${{ matrix.goVer }}
-        uses: actions/setup-go@v2
+        uses: actions/setup-go@v5
         with:
           go-version: ${{ matrix.goVer }}
         id: go
 
       - name: Check out code into the Go module directory
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up ANTLR
         env:
@@ -63,12 +39,20 @@ jobs:
           LOCATION=$PWD ./install.sh
 
       - name: Get dependencies
-        run: make install
+        run: make install && make install-tools
 
       - name: Generate
         run: |
           export PATH=$PATH:$HOME/antlr-bin
           make generate
+
+      - name: Lint
+        run: |
+          make vet
+          make lint
+          make fmt
+          git diff
+          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
 
       - name: Compile
         run: make compile
