Updated dependencies (#769)
* Updated dependencies

* Dropped pre-generics versions of Go

* Updated ANTRL

* Added staticcheck and goimports tools

* Updated build steps

* Fixed unit tests for http funcs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,12 +3,36 @@ name: build
 on: [push, pull_request]
 
 jobs:
+  analyze:
+    name: Static Analysis
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '>=1.19'
+
+      - name: Set up linters
+        run: make install-tools
+
+      - name: Lint
+        run: |
+          make vet
+          make lint
+          make fmt
+          git diff
+          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
+
   build:
     name: Build
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        goVer: [1.14, 1.15, 1.16, 1.17]
+        goVer: [1.18, 1.19]
     steps:
       - name: Set up Go ${{ matrix.goVer }}
         uses: actions/setup-go@v2
@@ -16,14 +40,17 @@ jobs:
           go-version: ${{ matrix.goVer }}
         id: go
 
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v2
+
       - name: Set up ANTLR
         env:
-          ANTLR_VERSION: 4.9
+          ANTLR_VERSION: 4.11.1
         run: |
           sudo curl -o /usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar https://www.antlr.org/download/antlr-${ANTLR_VERSION}-complete.jar
           export CLASSPATH=".:/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar:$CLASSPATH"
           mkdir $HOME/antlr-bin
-          echo -e '#!/bin/bash\njava -jar /usr/local/lib/antlr-4.9-complete.jar "$@"' > $HOME/antlr-bin/antlr
+          echo -e '#!/bin/bash\njava -jar /usr/local/lib/antlr-4.11.1-complete.jar "$@"' > $HOME/antlr-bin/antlr
           echo -e '#!/bin/bash\njava org.antlr.v4.gui.TestRig "$@"' > $HOME/antlr-bin/grun
           chmod +x $HOME/antlr-bin/*
           export PATH=$PATH:$HOME/antlr-bin
@@ -34,22 +61,8 @@ jobs:
           curl https://raw.githubusercontent.com/MontFerret/lab/master/install.sh -o install.sh
           sudo sh install.sh
 
-      - name: Set up linters
-        run: go install github.com/mgechev/revive@latest
-
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v2
-
       - name: Get dependencies
         run: make install
-
-      - name: Lint
-        run: |
-          make vet
-          make lint
-          make fmt
-          git diff
-          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
 
       - name: Generate
         run: |
